### ISSUE TITLE
Review __eq__ and __hash__ in Ref

### ISSUE THREAD

**Issue by rdemaria** [xsuite/xdeps#5]
Refs are used as keys in many dictionaries and sets and both behavior and performance are important.
Currently mutations of internal functions are allowed in refs and manager although not inherently safe.

Refs `__eq__` and `__req__` return an `BinOpRef`. Not clear if this can break expectations in collections since `hash` and `eq` are linked.

`__hash__` of  `Ref` ultimately rely on the `id` of the root object. It is probably not needed since refs define a formal relation.

A review is required at some point...

**Comment by giadarol** [comment]
Obsolete
